### PR TITLE
PreviewViewController Fixes

### PR DESCRIPTION
**Pull request by spacedrabbit**
### PR Highlights
- Finishes programmatic changes to `PreviewViewController`
- Creates `PreviewView` class
- Adds dynamic resizing to textview in `PreviewView`
- Adds automatic layout to `FoaasTextField` based on total # of text fields
- Adjusts scroll view in `PreviewView` in response to keyboard events

### Bugs
- Fixes an autolayout bug on `FoaasOperationTableViewCell` specific to iPhone7+
- Fixes an existing logic error with auto-laying out `FoaasTextField`

### CODE REVIEW

**Review by singhhari — APPROVED** [review]
👍🏼

**Comment by spacedrabbit** [comment]
merging request due to >24hr limit on review. ty to @harichandansingh for giving the thumbs up. @anama118118 @seymotom @liamdkane be more vigilant next time

**Review by seymotom — COMMENTED** [review]
👍

**Comment by anama118118** [comment]
👍🏼

**Pull request merged**
